### ISSUE TITLE
Does mybatis 3.2 must require log4j？

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mybatis/old-google-code-issues#793]
```
When I update mybatis from 3.1.1 to 3.2.0, my project run error. The error 
information like "... nested exception is java.lang.NoClassDefFoundError: 
org/apache/log4j/Priority; ..."So, I wonder does mybatis 3.2 must require 
log4j. This problem dispear when I add log4j to my project.Please check out, 3Q.
```

Original issue reported on code.google.com by `xuliag...@gmail.com` on 6 Mar 2013 at 5:55
- Merged into: #785
